import { AUTH } from '../Constants/types'

//QUEDO PENDIENTE CON EL SISTEMA DE AUTENTICACIÓN
//ANDO TRABAJANDO EN LA ACCIONES DE REDUX, Y EN LOS REQUEST AL API
//HAY QUE HACER AL BACKEND Y PREPARA TODO LO DE ESTE PARA EMPEZAR A VERIFICAR USUARIOS